### ISSUE TITLE
Text2Loc: 3D Point Cloud Localization from Natural Language

### ISSUE THREAD

**Issue by SS-hj** [dohyeonYoon/Deep-Learning-Paper-Review#3]
# Text2Loc: 3D Point Cloud Localization from Natural Language

#### Information
- 링크: [Link](https://arxiv.org/pdf/2311.15977)
- 저자: Xia, Yan, et al.
- 발표 연도: 2024
- 개제처: CVPR

**Comment by dohyeonYoon** [comment]
아래와 같이 message 안에 본인의 이슈번호를 연동해서 PR이 병합되면 자동으로 닫히도록 하는건 어떨까요?

$ git commit -m "Docs: Add paper review on LLM & Multi-modal, close #3"
