### ISSUE TITLE
Drag Your GAN: Interactive Point-based Manipulation on the Generative Image Manifold

### ISSUE THREAD

**Issue by SS-hj** [dohyeonYoon/Deep-Learning-Paper-Review#7]
# Drag Your GAN: Interactive Point-based Manipulation on the Generative Image Manifold

#### Information
- 링크: [Link](https://arxiv.org/pdf/2305.10973)
- 저자: Pan, Xingang, et al.
- 발표 연도: 2023
- 개제처: SIGGRAPH

**Comment by dohyeonYoon** [comment]
Issue에 라벨(논문 카테고리)을 깜빡 하신 것 같습니다 :)
